Issue 125 gradient
norse/norse pull request #127
Opened 2020-10-04 19:53 UTC by Jegp

Fixes issues with gradients not flowing correctly #125

2020-10-04 21:54 UTC, cpehle requested changes
LGTM (apart from typo). We should also adopt the convention used in LIFFeedForwardCell for the other Forward cells.

2020-10-04 21:54 UTC, cpehle commented on norse/torch/module/lif_mc.py
> +            state.v.requires_grade = True
Spelling error?

2020-10-05 07:58 UTC, Jegp commented on norse/torch/module/lif_mc.py
> +            state.v.requires_grade = True
Indeed. And unnecessary so I deleted it

2020-10-05 08:04 UTC, cpehle approved these changes

2020-10-05 09:30 UTC, merged