Feature lif adex recurrent refrac
norse/norse pull request #291
Opened 2022-01-13 21:10 UTC by Pugavkomm

2022-01-21 11:26 UTC, Jegp requested changes
Thanks for the addition! I hope you understand that my comments about the testing relate to regression/completeness further down the line. If we modify something in the future, it's helpful to know that we don't mess up the neuron logic :-)

2022-01-21 11:26 UTC, Jegp commented on norse/torch/module/__init__.py
> +    # LIFAdExRafrac
Can this be removed?

2022-01-21 11:26 UTC, Jegp commented on norse/torch/functional/test/test_lif_adex_refrac.py
> +        _, s = lif_adex_refrac_step(x, s, input_weights, recurrent_weights)
I appreciate that you're testing this. I would perhaps suggest adding a test for the numerical output, just so there is some checks against the correctness of the calculations.

2022-01-21 11:26 UTC, Jegp commented on norse/torch/functional/test/test_lif_adex_refrac.py
> +        _, s = lif_adex_refrac_feed_forward_step(x, s)
Same as above. Could you add some numerical validation?

2022-04-25 12:00 UTC, cpehle approved these changes
I think this is pretty good as is. We should write numerical tests of the AdEX equations ideally against other simulators, still. But this goes beyond just asserting the values that the integration happens to produce, but instead we could look into reproducing the Naud patterns for example. But this is for another submission, I think.

2023-01-13 11:07 UTC, merged

2023-01-13 12:40 UTC, Jegp commented
Thank you for merging this @cpehle ! And sorry for dragging my feet @Pugavkomm