Feature lif box
norse/norse pull request #362
Opened 2023-02-14 22:11 UTC by theLamentingGirl

Hi, I created a LIFBox class that wraps around the LIFBoxCell. Also created a test function for the module. Please review :)

2023-02-15 15:09 UTC, Jegp requested changes
Nice work! Could I ask you to look at two (minor) things?

1. You seem to have many changes in unrelated files. Which is not necessarily bad, but may indicate formatting issues. Could you run this by the [black](https://github.com/psf/black) formatter (`black .`) to just make sure everything is formatted neatly.
2. You also add a functional version of the lif_box (which is nice)! But could you kindly copy a test in for that as well? (in `norse/torch/functional/test`?) That will be super helpful for regressions.

2023-03-01 21:14 UTC, cpehle requested changes
Can you please move all changes related to encoding and the associated tests to a separate pull request? They look good, but each pull request should correspond to a specific change.

2023-03-01 21:14 UTC, cpehle commented on .gitignore
> +norse/torch/functional/rough.py
where is this coming from

2023-03-01 21:14 UTC, cpehle commented on norse/torch/functional/encode.py
> +    generator: torch.Generator = None,
please open a separate pull request for this

2023-03-01 21:14 UTC, cpehle commented on norse/torch/functional/encode.py
> +        torch.rand(seq_length, *input_values.shape, device=input_values.device,generator = generator).float()
same here

2023-03-01 21:14 UTC, cpehle commented on norse/torch/functional/encode.py
> +    generator: torch.Generator = None,
and here

2023-03-01 21:14 UTC, cpehle commented on norse/torch/functional/encode.py
> +    generator: torch.Generator = None,
and here

2023-03-01 21:14 UTC, cpehle commented on norse/torch/functional/test/test_encode.py
> +    poisson_encode,
and here

2023-03-01 21:14 UTC, cpehle commented on norse/torch/functional/test/test_encode.py
> +def test_poisson_encode():
not related

2024-03-18 22:11 UTC, Jegp commented
I'll close this for now. Happy to reopen later :)

2024-03-18 22:11 UTC, closed without merging